config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "Clubhouse", root_path, class: "navbar-item is-size-5"%>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">

    <div class="navbar-end">
      <% if user_signed_in? %>
        <div class="navbar-item">
          <%= link_to "New post", new_post_path, class: "button is-light" %>
        </div>
        <div class="navbar-item has-dropdown is-hoverable">
          <%= link_to current_user.username, "#", class: "navbar-link" %>
          <div class="navbar-dropdown">
            <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-item" %>
            <hr class="navbar-divider" />
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-item" %>
      <% else %>
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to "Sign up", new_user_registration_path, class: "button is-dark" %>
            <%= link_to "Log in", new_user_session_path, class: "button is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/posts/_feed.html.erb
<div class="column is-half is-offset-one-quarter">
  <% if user_signed_in? %>
	  <article class="media box">
	  	<figure class="media-left">
	  		<p class="image is-64x64">
	  			<img src="https://bulma.io/images/placeholders/64x64.png">
	  		</p>
	  	</figure>
	  	<div class="media-content">
	  		 <%= render "posts/form" %>
	  	</div>
	  </article>
  <% end %>
  <% @posts.each do | post |%>
    <div class="box">
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <% if user_signed_in? %>
              <p><%= post.user.username %></p>
            <% else %>
              <p>Anon</p>
            <% end %>
            <p>
              <strong><%= post.title %>: </strong>
              <%= post.body %>
            </p>
          </div>
          
          <nav class="level">
            <div class="level-left is-mobile">
              <%= link_to post, class: "level-item" do%>
                <span class="icon"><%= fa_icon "link" %></span>
              <% end %>
            <% if user_signed_in? && current_user.id == post.user.id %>
              <%= link_to edit_post_path(post), class: "level-item" do%>
                <span class="icon"><%= fa_icon "pencil" %></span>
              <% end %>
              <%= link_to post, method: :delete, class: "level-item",
                  data: { confirm: "Are you sure you want to delete this post?"} do%>
                <span class="icon"><%= fa_icon "trash-o" %></span>
              <% end %>
            <% end %>
            </div>
          </nav>
        </div>
      </article>
    </div>
  <% end %>
</div>
              
            
            

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="field">
    <div class="control">
      <%= f.input :title, label: "Title", input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }, placeholder: "Cool title goes here", autofocus: true %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :body, label: "Body", input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" }, placeholder: "Compose a new post", autofocus: true %>
    </div>
  </div>
  

  <%= f.button :submit, class: "button is-warning" %>
<% end %>

app/views/posts/edit.html.erb
<section class="section">
  <div class="container">
   <div class="column is-half">
     <h1 class="title">Edit post</h1>
     <%= render "posts/form", post: @post%>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render "posts/feed"%>
    </div>
  </div>
<section>

app/views/posts/new.html.erb
<section class="section">
  <div class="container">
   <div class="column is-half">
     <h1 class="title">Create a new post</h1>
     <%= render "posts/form", post: @post%>
    </div>
  </div>
</section>

<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to "Cancel", posts_path, class: "button is-dark"%>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/posts/show.html.erb
<section class="section">
  <div class="container">
    <h2 class="title"><%= @post.title %></h2>
    <p class="is-size-5"><%= @post.body %>
  </div>
</section>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>